### ISSUE TITLE
module 'pytorch3d.renderer.compositing' has no attribute 'CompositeParams'

### ISSUE THREAD

**Issue by FengQiaojun** [facebookresearch/synsin#18]
Hi,

Thanks for sharing this! I was running the [Simple Demo.ipynb](https://github.com/facebookresearch/synsin/blob/master/demos/Simple%20Demo.ipynb) and got this error
![Screenshot from 2020-07-14 17-17-41](https://user-images.githubusercontent.com/32551664/87488745-fec1e200-c5f5-11ea-8e43-6e03040cba60.png)
It seems that pytorch3d v0.2.0 removed compositing.CompositeParams. Also the fourth param of compositing function is not used anywhere in [compositing.py](https://github.com/facebookresearch/pytorch3d/blob/v0.2.0/pytorch3d/renderer/compositing.py#L70). 
`def alpha_composite(pointsidx, alphas, pt_clds, blend_params=None)`
The blend_params is not used.

Does this change matter? Then we need to change [models/layers/z_buffer_layers.py](https://github.com/facebookresearch/synsin/blob/master/models/layers/z_buffer_layers.py) according right? I tried to comment out every "params" and it worked. Is it the right solution?

**Comment by gkioxari** [comment]
Yes we removed CompositeParams because it was not used anywhere. The `blend_params` in `alpha_composite` or the other composite functions was actually not passed in to the actual compositing source, which I think is what you noted too in your text. The `radius` came only in to play here:
https://github.com/facebookresearch/synsin/blob/82ff948f91a779188c467922c8f5144018b40ac8/models/layers/z_buffer_layers.py#L82

This is why we decided to remove it to clean the codebase up and not cause confusion. Maybe @oawiles can verify whether our change breaks the SynSin codebase.

**Comment by oawiles** [comment]
Yeah I think as Georgia said this won't actually make a difference as it wasn't used. What you did @FengQiaojun should be fine. You can always double check by running a notebook and comparing the output with your code to the preloaded values.

**Comment by gkioxari** [comment]
@oawiles Should we fix it in the codebase?! Or @FengQiaojun once you verify the results as @oawiles suggested do you want to submit a PR to propagate the fix to the codebase?

**Comment by oawiles** [comment]
If @FengQiaojun wants to submit a PR I don't see why not! I can double-check the PR to make sure that it looks ok. But I think the only thing that was passed in the params was the radius, so provided that's set correctly that should be it!

**Comment by FengQiaojun** [comment]
OK I submitted one PR in [https://github.com/facebookresearch/synsin/pull/19](https://github.com/facebookresearch/synsin/pull/19). More info provided there.
Thanks!
