### ISSUE TITLE
In the demo notebook in the 'Load the dataset' cell I'm missing a dataset

### ISSUE THREAD

**Issue by MotorCityCobra** [facebookresearch/synsin#8]
I downloaded the models and those load, but I get

`OSError: /checkpoint/ow045820/data/realestate10K/RealEstate10K//frames/train/video_loc.txt not found.`

When I try to run the cell 'Load the dataset' in the 'Interactive Demo' notebook.

**Comment by oawiles** [comment]
The video_loc.txt we created in order to deal with frames or videos that may be removed from YouTube. It simply contains the successfully processed frames in the text file. This is described here: https://github.com/facebookresearch/synsin/blob/master/REALESTATE.md. You can of course modify how this works to not require the video_loc.txt

**Comment by MotorCityCobra** [comment]
>You can of course modify how this works to not require the video_loc.txt

Do I need this dataset to run the Interactive Demo notebook?
Where do I download it to?
What do I modify to not require video_loc.txt?

**Comment by oawiles** [comment]
To run that notebook, yes you need the dataset. The instructions are in the linked file above.

To run the simpler demo: https://github.com/facebookresearch/synsin/blob/master/demos/Simple%20Demo.ipynb. You do not need any dataset.

**Comment by MotorCityCobra** [comment]
I don't know where to begin how many problems I'm having now. On the page `https://google.github.io/realestate10k/download.html`
The download link will not download via the commandline with `wget https://storage.cloud.google.com/realestate10k-public-files/RealEstate10K.tar.gz`

There are no instructions on where the notebook wants the dataset to be in the link.
There is nothing about where to " modify how this works to not require the video_loc.txt".

Most notebooks just download the dataset if it's not stored locally.

**Comment by oawiles** [comment]
Unfortunately, we can't just make the dataset available to be downloaded due to IP reasons; hence we explain how to download the dataset in the [readme file ](https://github.com/facebookresearch/synsin/blob/master/REALESTATE.md). This is why it has to be downloaded by the user following these instructions. If you don't want to have to download the dataset, you can use the 'Simple Demo' notebook I linked above. This requires no dataset.

I am a PhD student. I no longer work at Facebook.

**Comment by MotorCityCobra** [comment]
I'm getting
`AttributeError: 'RealEstate10K' object has no attribute 'imageset'`

**Comment by MotorCityCobra** [comment]
I don't mean to be rude, but I don't understand why I have to labor over this for 6 hours. Where does the dataset go? Why do you make users solve these puzzles instead of just making it work out of the box?

**Comment by gkioxari** [comment]
Let's get things clear here. Ok you are having difficulties with the repo. Life is hard. You will figure it out. But if you try again to fish for comments with some article or ask folks where they work, which is none of your goddamn business, I will have you blocked from all facebookresearch github accounts.

**Comment by MotorCityCobra** [comment]
I'm sorry. I didn't mean to cross boundaries.

If I got more than "it's in the link" (it wasn't in the link) or "you'll figure it out", people with the same problem with this new repo in the future would be able to see my Q and your A, that is, if it answered the question.

As far as my question about Facebook, it's clearly some kind of military technology deployed for counter-insugancy purposes against the now locked down public and Mark Zuckerberg is an actor.

**Comment by gkioxari** [comment]
@oawiles has given you instructions on how to download the dataset. @oawiles also explained why we can't provide the dataset ourselves (tl;dr legal issues). So yes, you need to try a little bit to download the dataset in order to use the demo. I understand that some might find it harder than others to set it up, and we are happy to answer questions. 

The rest of your questions and mentions are completely irrelevant. You keep insisting on mentioning things unrelated to this repo, and your commentary on "on the record" statements is really pushing it for me. One more strike, and you're blocked.

**Comment by MotorCityCobra** [comment]
> I understand that some might find it harder than others to set it up, and we are happy to answer questions.

Okay, sorry. I got that far.  
I have the dataset and I commented out the video_loc.txt lines.  
I have the dataset in a folder called `RealEstate10K` with train and test dirs inside of it.  
I put the folder in the main directory. I copied the folder into the data directory.  
I get `AttributeError: 'RealEstate10K' object has no attribute 'imageset'`

**Comment by MotorCityCobra** [comment]
I know I'm down to the issue of where the folder of the `RealEstate10K` goes.
I see it's looking in some place `opt.train_data_path =("/checkpoint/ow045820/data/realestate10K/RealEstate10K/")`
in `/options/options.py`

**Comment by MotorCityCobra** [comment]
> You can of course modify how this works to not require the video_loc.txt


Can we go back to focussing on this step?

**Comment by MotorCityCobra** [comment]
>https://github.com/facebookresearch/synsin/blob/master/REALESTATE.md

"The frames need to be extracted based on the text files; we extract them to: ${REAL_ESTATE_10K}/frames"

With what? How?

**Comment by MotorCityCobra** [comment]
Are you really happy to answer questions?
Do I use youtube-dl to download each video and ffmpeg to convert each frame to png?  
I have never seen anything like this.

**Comment by MotorCityCobra** [comment]
THanks

**Comment by MotorCityCobra** [comment]
gkioxari  you and the other one should not be answering questions for this repo. YOu are elitist diversity hires who think you are superior because you make $110k a year and pay most of it to live in a studio apartment with roommates. You are a blight on the industry. As the grains of sand pour through the hour glass you grow closer to the cool wine cat lady life of oblivion.
