### ISSUE TITLE
I downloaded the RealEstate10K dataset. Where does it go?

### ISSUE THREAD

**Issue by MotorCityCobra** [facebookresearch/synsin#9]
Does the `Interactive Demo` extract the frames?

[this](The frames need to be extracted based on the text files; we extract them to: ${REAL_ESTATE_10K}/frames.) says...  
"The frames need to be extracted based on the text files; we extract them to: ${REAL_ESTATE_10K}/frames."  

How do "we" do that?

**Comment by oawiles** [comment]
No it doesn't. You need to follow the instructions for RealEstate10K from THEIR [website](https://google.github.io/realestate10k/). We can't distribute the original frames because (1) there's a huge number -- the memory would be too much -- and (2) for IP reasons.

We then have one change (which we discuss in the file you quoted from above). Their dataset is based on youtube data, which means videos/frames may be missing as hte dataset may change over time. As a result, we save the information about the frames that were correctly extracted.

**Comment by phongnhhn92** [comment]
@oawiles I guess you are not allowed to distribute the extracted frames but I guess you can share the script which you have used to preprocess the data (downloading the video and possibly resize, change intrinsic parameters). I myself have made one but I guess it would be helpful not only for me for comparison but also easier for other people to work faster on your method. 

However, I believe that this is just a simple python script that anyone with basic Python skill can do so may be it is not that worth considering anymore :D

**Comment by oawiles** [comment]
Thank you @phongnhhn92 ! 

We would have given the script but can't distribute that -- it is too similar to simply distributing the frames. But as you say, it is a simple python script that simply extracts frames at the timestamps and resizes them.

**Comment by MotorCityCobra** [comment]
phongnhhn92 
Thank you for the response. Can I ask what frame rate you used to extract the pictures?

**Comment by MotorCityCobra** [comment]
What are the png frames to be named individually?
`${REAL_ESTATE_10K}/frames/train/${path_totrain_vid1}/*.png`

Are they named after their timestamp number in microseconds?
